version: "3.8"
services:
  tomcat:
    image: tomcat:9.0
    working_dir: /usr/local/tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
    environment:
      - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom

  compiler:
    image: maven:3.9.4-eclipse-temurin-17
    working_dir: /app
    volumes:
      - .:/app
    command: ["tail", "-f", "/dev/null"]
